stages:
  - build
  - test
  - coverage

test:
  stage: test
  image: python:3.12
  script:
    - pip install hatch
    - hatch test

coverage:
  stage: coverage
  image: python:3.12
  script:
    - pip install hatch
    - hatch test --cover
  coverage: '/TOTAL.+?(\d+\%)$/'
  only:
    - main

build_stable:
  stage: build
  image: python:3.12
  script:
    - echo "Déploiement my-arithmetic-$USER sur les serveurs stables"
    - pip install hatch hatch-vcs
    - hatch build
    - ls dist/
  only:
    - tags

build_non_stable:
  stage: build
  image: python:3.12
  script:
    - echo "Déploiement my-arithmetic-$USER sur les serveurs develop"
    - pip install hatch hatch-vcs
    - hatch build
    - ls dist/
  only:
    - develop