stages:
  - build
  - test
  - coverage

test:
  stage: test
  image: python:3.12
  script:
    - pip install hatch
    - hatch test

build:
  stage: build
  image: python:3.12
  script:
    - pip install hatch
    - pip install hatch-vcs
    - hatch build
    - ls dist/
  only:
    - tags

coverage:
  stage: coverage
  image: python:3.12
  script:
    - pip install hatch
    - hatch test --cover
  coverage: '/TOTAL.+?(\d+\%)$/'
  only:
    - main